
const LANDUSE_CLEAR = 'landuse/LANDUSE_CLEAR';
const LANDUSE_DIDFETCH = 'landuse/LANDUSE_DIDFETCH';
const LANDUSE_WILLFETCH = 'landuse/LANDUSE_WILLFETCH';
const LANDUSE_DIDUPDATE = 'landuse/LANDUSE_DIDUPDATE';
const LANDUSE_WILLUPDATE = 'landuse/LANDUSE_WILLUPDATE';

export default {
    LANDUSE_CLEAR,
    LANDUSE_DIDFETCH,
    LANDUSE_WILLFETCH,
    LANDUSE_DIDUPDATE,
    LANDUSE_WILLUPDATE,
}