
const IRDATA_DIDFETCH = 'map/IRDATA_DIDFETCH';
const IRDATA_WILLFETCH = 'map/IRDATA_WILLFETCH';
const SITE_DELETE = 'map/SITE_DELETE';
const SITES_DIDFETCH = 'map/SITES_DIDFETCH';

export default {
    IRDATA_DIDFETCH,
    IRDATA_WILLFETCH,
    SITE_DELETE,
    SITES_DIDFETCH
}