
const LANDUSE_EDIT = 'ui/LANDUSE_EDIT';
const QUERY_DELETE = 'ui/QUERY_DELETE';
const QUERY_INSERT = 'ui/QUERY_INSERT';
const QUERY_TOGGLEOPEN = 'ui/QUERY_TOGGLEOPEN';
const QUERY_TOGGLEVISIBLE = 'ui/QUERY_TOGGLEVISIBLE';
const RESULTITEM_MENUOPEN = 'ui/RESULTITEM_MENUOPEN';
const RESULTS_CLEARSELECTION = 'ui/RESULTS_CLEARSELECTION';
const RESULTS_SELECT = 'ui/RESULTS_SELECT';
const SITES_CLEARSELECTION = 'ui/SITES_CLEARSELECTION';
const SITE_DELETE = 'ui/SITE_DELETE';
const SITES_INSERT = 'ui/SITES_INSERT';
const SITES_SETSELECTED = 'ui/SITES_SETSELECTED';
const SITES_SETZOOMTO = 'ui/SITES_SETZOOMTO';

export default {
    LANDUSE_EDIT,
    QUERY_DELETE,
    QUERY_INSERT,
    QUERY_TOGGLEOPEN,
    QUERY_TOGGLEVISIBLE,
    RESULTITEM_MENUOPEN,
    RESULTS_CLEARSELECTION,
    RESULTS_SELECT,
    SITE_DELETE,
    SITES_CLEARSELECTION,
    SITES_INSERT,
    SITES_SETSELECTED,
    SITES_SETZOOMTO
}